# Generated by Django 6.0 on 2026-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Experience top-tier performance with our latest hardware.'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.TextField(blank=True, help_text='List specifications here', null=True),
        ),
    ]
