# Generated by Django 6.0 on 2026-01-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_product_description_product_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=200)),
                ('card_expiry', models.CharField(max_length=10)),
                ('card_cvv', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='....'),
        ),
    ]
